import Head from 'next/head'
import WebLayout from "../components/Layout/WebLayout";
import Header from '../components/Web/Header'
import Introduction from '../components/Web/Introduction'
import Features from '../components/Web/Features'
import Detail from '../components/Web/Detail';
import DetailImage1 from '../public//images/details-1.jpg'
import Counter from '../components/Web/Counter';
import Slider  from '../components/Web/Slider';
import Download from '../components/Web/Download';
import Footer from '../components/Web/Footer';




export default function Home() {
  return (
    <>
      <Head>
        <title>Ubyco || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Introduction />
      <Features/>
      <Detail src={DetailImage1} type='right'>
          <h1>Life is good</h1>
          <p>I blieve it good</p>
          <p> Let do it again</p>
      </Detail>

      <Detail src={DetailImage1} type='left'>
          <h1>Life is good</h1>
          <p>I blieve it good</p>
          <p> Let do it again</p>
      </Detail>

      <Detail src={DetailImage1} type='right'>
          <h1>Life is good</h1>
          <p>I blieve it good</p>
          <p> Let do it again</p>
      </Detail>
      <Counter />

      <Slider/>
      <Download />
      <Footer/>

    </>
  )
}

Home.Layout = WebLayout;
